let wertick = require("./../../lib/main.js").default;

wertick.run({
	name: "Wapgee",
	mode: "development",
	port: "1200",
	jwtSecret: "v1s4LIGdBu",
	dbUsername: "root",
	dbPassword: "root",
	dbName: "graphql",
	dbHost: "localhost",
	dbPort: "3306",
	logging: "false",
	allowGraphql: "TRUE",
	modulesEnabled:" ",
	predefinedModules: "user,forgetPassword,permission,role,rolePermission,userRole,userPermission,profile,auth",
	dialect: "MONGO_DB",
	mongoURI: "mongodb://ilyas:pass1234@ds027719.mlab.com:27719/graphql",
	mailerService: "gmail",
	mailerServiceUsername: "jangonewsmailer@gmail.com",
	mailerServicePassword: "jango/12345",
	backendApp: "http://localhost:1200",
	frontendAppUrl: "http://localhost:3000",
	frontendAppPasswordResetUrl: "/reset-password/",
});